# Generated by Django 3.1.7 on 2021-04-27 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210417_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='auctionlisting',
            name='startDate',
        ),
    ]
