# Generated by Django 3.1.7 on 2021-05-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210510_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='currentBid',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='currentBid_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
